// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVZAz5Quyf6_LQxYr_We85DcGLC-3CvbE',
    appId: '1:1080670586999:web:bc97430c30610e268f5e72',
    messagingSenderId: '1080670586999',
    projectId: 'park-manager-b0b4a',
    authDomain: 'park-manager-b0b4a.firebaseapp.com',
    storageBucket: 'park-manager-b0b4a.appspot.com',
    measurementId: 'G-R2NF60Q019',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnaULA64H9TL8RF-G3obapXkG6PsZLWTo',
    appId: '1:1080670586999:android:69ac778be5fe0ca28f5e72',
    messagingSenderId: '1080670586999',
    projectId: 'park-manager-b0b4a',
    storageBucket: 'park-manager-b0b4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyUB3ZvrwdWAde-wMyZH9eIH4cgkPfkGM',
    appId: '1:1080670586999:ios:923f00bde9b3b77c8f5e72',
    messagingSenderId: '1080670586999',
    projectId: 'park-manager-b0b4a',
    storageBucket: 'park-manager-b0b4a.appspot.com',
    iosBundleId: 'com.example.parkManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyUB3ZvrwdWAde-wMyZH9eIH4cgkPfkGM',
    appId: '1:1080670586999:ios:2b3bddae3ec9a0dd8f5e72',
    messagingSenderId: '1080670586999',
    projectId: 'park-manager-b0b4a',
    storageBucket: 'park-manager-b0b4a.appspot.com',
    iosBundleId: 'com.example.parkManager.RunnerTests',
  );
}
